### ISSUE TITLE
特征txt

### ISSUE THREAD

**Issue by Milittle** [fucusy/gait-energy-image-recognition#1]
请问一下作者，特征的txt文件是怎么获取到的

**Comment by fucusy** [comment]
那个txt？

**Comment by fucusy** [comment]
哪个？

**Comment by Milittle** [comment]
config.project.joint_feature_di这个路径下的

**Comment by Milittle** [comment]
![image](https://user-images.githubusercontent.com/9550695/32689270-4f790cea-c71c-11e7-8f6b-f9fd8cc71f53.png)

**Comment by fucusy** [comment]
it is not used anymore, version is always 2, I will delete those code at next commit

**Comment by Milittle** [comment]
thanks

**Comment by fucusy** [comment]
I am figuring out what happened when version is 2

**Comment by Milittle** [comment]
what happened？

**Comment by fucusy** [comment]
You may try to checkout `gei` branch, I think the master branch does not work.

**Comment by fucusy** [comment]
closed this issue please, if you get the answer

**Comment by Milittle** [comment]
i clone this repository，and i only have ‘gei’ branch

**Comment by fucusy** [comment]
If you are in `gei` branch, there is no `config.project.joint_feature_dir`,  [config.py](https://raw.githubusercontent.com/fucusy/gait-energy-image-recognition/gei/config.py)

**Comment by fucusy** [comment]
Two branches are available, `master` and `gei`, you may in `master` branch.

**Comment by Milittle** [comment]
ok, i get it, thank you so much, i will close this issue.
