### ISSUE TITLE
about run

### ISSUE THREAD

**Issue by Milittle** [fucusy/gait-energy-image-recognition#2]
![image](https://user-images.githubusercontent.com/9550695/32690332-0fb9261c-c730-11e7-8906-335328c0484a.png)
Could you solve this problem？thanks

**Comment by Milittle** [comment]
i already use google，but i do not search answer.

**Comment by fucusy** [comment]
What's your scikit-learn version?

**Comment by Milittle** [comment]
What is yours?, my scikit-learn is default, maybe some package is depend on scikit-learn, when i install other package and this scikit-learn is installed.

**Comment by Milittle** [comment]
I will check version in tomorrow. today i already come back dormitory.Anyway, thank you.

**Comment by fucusy** [comment]
scikit-learn (0.18.1)

**Comment by Milittle** [comment]
my scikit-learn version is 0.19.1，how should i install version 0.18.1 using `pip command`? thanks

**Comment by Milittle** [comment]
I already install using `pip command`, thank you.

**Comment by Milittle** [comment]
but the error still show. you know its solution?

**Comment by fucusy** [comment]
sorry, it should be scikit-learn (0.17.1)

**Comment by Milittle** [comment]
ok，the error is gone. thank you

**Comment by chalotrakunal** [comment]
![screenshot from 2018-11-24 19-48-58](https://user-images.githubusercontent.com/31889898/48969237-077d3300-f022-11e8-96a0-6dc0b60b4fa9.png)


how to resolve this problem sir??
